[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback: любые пути -> index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ассеты кэшируем надолго (именные по хэшу)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# index.html — без кэша
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"

# Твой блок для SW
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"
